version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: dndPrivate
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  redis:
    image: redis
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

  springbootapp:
    build: .
    environment:
      TZ: Asia/Seoul
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
