version: '3'
services:
  app:
    image: rlaehddnd0422/dnd
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - nginx
#      - db
#  db:
#    image: mysql:latest
#    restart: always
#    env_file:
#      - application-secret.yml
#    volumes:
#      - db_data:/var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
volumes:
  db_data: