version: '3'
services:
  app:
    image: rlaehddnd0422/dnd
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    env_file:
      - application-secret.yml
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: