spring:
  profiles:
    include: secret

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${custom.db.url}'
    username: '${custom.db.username}'
    password: '${custom.db.password}'
    redis:
      host: '${redis.host}'
      port: 6379

  session:
    store-type: redis

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: '${kakao.client.id}'
            client-secret: '${kakao.client.secret}'
            client-authentication-method: client_secret_post
            redirect-uri: '${kakao.redirect-url}'
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret_key: ${jwt.secret.secret_key}
  access-token-validity-in-seconds: 86400 # (배포 시 30분 -> 1800 설정)
  refresh-token-validity-in-seconds: 86400 # (배포 시 1일 -> 86400설정)

cloud:
  aws:
    s3:
      bucket: '${cloud.aws.s3.bucket}'
      url: '${cloud.aws.s3.url}'
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: '${cloud.aws.s3.credentials.accessKey}'
      secretKey: '${cloud.aws.s3.credentials.secretKey}'

